/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the login screen may offer. Unauthenticated. */
        get: operations["getAuthConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local sign-in. Sets the session cookie. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirects the browser to the identity provider. */
        get: operations["startOIDC"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity-provider redirect target. On success sets the session cookie and redirects to `/`; on refusal redirects to `/login?error=<code>` with one of `oidc_forbidden`, `oidc_failed`. */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the caller's password. `currentPassword` is required unless the session is restricted (the temporary password was proved at sign-in). */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyTokens"];
        put?: never;
        post: operations["issueMyToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeMyToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Addresses the connection instructions are rendered from. */
        get: operations["getConnectInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/admin/users/{userId}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new temporary password. The user must change it at next sign-in. */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a fresh identity-provider invitation for a human who has not linked an identity yet (the old one lapsed or was consumed without a link). Replaces any previous invitation for that account. */
        post: operations["renewUserInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUserTokens"];
        put?: never;
        /** Issue a token on behalf of an account — the only way a service account gets one. */
        post: operations["issueUserToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeUserToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers and the models they serve right now, for the policy editor. */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/policy/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Which models of today's catalogue a set of rules covers. A wildcard rule also covers models published later; the preview can only show today's. */
        post: operations["previewPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviderAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startProviderLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers/login/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeProviderLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeProviderAccount"];
        options?: never;
        head?: never;
        patch: operations["updateProviderAccount"];
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        /** Validate, and unless `dryRun`, apply. The response always carries the diff against the running configuration, so the client can show it before applying. */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrices"];
        put: operations["replacePrices"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Stable machine code. The client translates this, not `message`.
             * @example invalid_credentials
             */
            code: string;
            /** @description English diagnostic for logs. Not for display. */
            message: string;
            /** @description The request field the error is about, when there is one. */
            field?: string;
        };
        AuthConfig: {
            /** @description Whether the email-and-password form is offered. */
            localLogin: boolean;
            oidc: {
                enabled: boolean;
                /** @description Button label, e.g. the identity provider's name. */
                displayName?: string;
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PasswordChangeRequest: {
            /** @description Required on a full session. */
            currentPassword?: string;
            newPassword: string;
        };
        /** @enum {string} */
        Kind: "human" | "service";
        /** @enum {string} */
        Role: "user" | "admin";
        /** @enum {string} */
        Status: "active" | "blocked";
        /**
         * @description `idp` means the policy is recomputed from group claims at every sign-in and is read-only here.
         * @enum {string}
         */
        PolicySource: "local" | "idp";
        /** @description Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later. */
        Policy: string[];
        Me: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["Kind"];
            email?: string | null;
            displayName: string;
            role: components["schemas"]["Role"];
            /** @description True while a temporary password has not been changed. */
            restricted: boolean;
            policy: components["schemas"]["Policy"];
            policySource: components["schemas"]["PolicySource"];
        };
        Token: {
            /** Format: uuid */
            id: string;
            label: string;
            /** @description The first characters of the secret, to tell keys apart. */
            prefix: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Null if the token was never used.
             */
            lastUsedAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
        };
        IssueTokenRequest: {
            /** @description Printable text; control characters are refused. */
            label: string;
        };
        IssuedToken: {
            token: components["schemas"]["Token"];
            /** @description The full API token. Shown once. */
            secret: string;
        };
        Usage: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** @enum {string} */
            bucket: "hour" | "day";
            totals: {
                /** @description Served requests. An attempt the gateway retried on another account is not counted twice; failed attempts are not counted. */
                requests: number;
                /** @description Every token spent, including tokens of failed or retried attempts. */
                tokensTotal: number;
            };
            points: {
                /**
                 * Format: date-time
                 * @description Start of the bucket.
                 */
                at: string;
                model: string;
                /** @description Served requests in this bucket, as in `totals.requests`. */
                requests: number;
                tokensTotal: number;
            }[];
        };
        ConnectInfo: {
            /** @description Public base URL of the proxied API, without a trailing slash. */
            apiBaseURL: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["Kind"];
            email?: string | null;
            displayName: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["Status"];
            policy: components["schemas"]["Policy"];
            policySource: components["schemas"]["PolicySource"];
            mustChangePassword: boolean;
            /** @description Sign-in methods that work now: `password` when a usable (unexpired) password is set, `oidc` when an identity-provider identity is linked. Empty for a service account and for a person whose only way in is a pending invitation. */
            signIn: ("password" | "oidc")[];
            /**
             * Format: date-time
             * @description Set while an identity-provider invitation exists and no identity is linked yet; it may lie in the past (lapsed - renew it with POST .../invitation).
             */
            invitationExpiresAt?: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateUserRequest: {
            kind: components["schemas"]["Kind"];
            /** @description Required for a human. Absent for a service account. */
            email?: string;
            displayName: string;
            role?: components["schemas"]["Role"];
            policy: components["schemas"]["Policy"];
            /**
             * @description For a human only. `password` issues a temporary password; `oidc` records an invitation the first sign-in with that address through the identity provider will claim. Ignored for a service account.
             * @enum {string}
             */
            signIn?: "password" | "oidc";
        };
        CreatedUser: {
            user: components["schemas"]["AdminUser"];
            temporaryPassword?: components["schemas"]["TemporaryPassword"];
        };
        TemporaryPassword: {
            /** @description Shown once. */
            password: string;
            /** Format: date-time */
            expiresAt: string;
        };
        UpdateUserRequest: {
            displayName?: string;
            role?: components["schemas"]["Role"];
            status?: components["schemas"]["Status"];
            policy?: components["schemas"]["Policy"];
        };
        Activity: {
            requests: {
                /** Format: date-time */
                at: string;
                /** Format: uuid */
                tokenId?: string | null;
                provider: string;
                model: string;
                stream: boolean;
                statusCode: number;
                tokensTotal: number;
                latencyMs: number;
            }[];
            audit: {
                /** Format: date-time */
                at: string;
                /**
                 * @example token.issue
                 * @example token.revoke
                 * @example user.policy.update
                 * @example auth.sign_in
                 */
                action: string;
                target?: string;
                /** Format: uuid */
                actorId?: string | null;
                detail?: {
                    [key: string]: unknown;
                };
            }[];
        };
        Catalog: {
            providers: {
                /** @description The provider name as written in policy rules. */
                name: string;
                models: string[];
            }[];
        };
        PolicyPreviewRequest: {
            rules: components["schemas"]["Policy"];
        };
        PolicyPreview: {
            errors: {
                rule: string;
                /** @example invalid_rule */
                code: string;
            }[];
            /** @description Models of today's catalogue the rules allow. */
            covered: {
                provider: string;
                model: string;
            }[];
        };
        ProviderAccount: {
            id: string;
            /** @description Policy-facing provider name. */
            provider: string;
            label?: string;
            email?: string | null;
            /**
             * @example active
             * @example error
             * @example disabled
             */
            status: string;
            disabled: boolean;
            lastError?: string | null;
            /** Format: date-time */
            lastRefreshedAt?: string | null;
            /** @description Direct vendor signals. No capacity estimate. */
            quota: {
                /**
                 * @example 5h
                 * @example 7d
                 */
                window: string;
                usedRatio: number;
                /** Format: date-time */
                resetAt?: string | null;
                /** Format: date-time */
                observedAt?: string | null;
            }[];
        };
        ProviderLoginStartRequest: {
            /** @enum {string} */
            provider: "claude" | "chatgpt";
        };
        ProviderLoginSession: {
            sessionId: string;
            /** @description Open in the administrator's own browser. */
            authURL: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ProviderLoginCompleteRequest: {
            sessionId: string;
            /** @description The full URL the vendor sign-in ended on. */
            callbackURL: string;
        };
        Settings: {
            /** @description The editable part of the upstream configuration as YAML. Fields the gateway owns (listen address, auth directory, management, config API keys) are absent and cannot be set. */
            yaml: string;
            /** @description The same values as typed form fields. */
            fields: {
                proxyURL?: string;
                requestRetry?: number;
                /** @description Seconds. */
                maxRetryInterval?: number;
            };
        };
        SettingsUpdateRequest: {
            /** @description Replaces the whole editable document. Mutually exclusive with `fields`. */
            yaml?: string;
            /** @description Patches individual typed fields. Mutually exclusive with `yaml`. */
            fields?: {
                proxyURL?: string;
                requestRetry?: number;
                maxRetryInterval?: number;
            };
            /** @default false */
            dryRun: boolean;
        };
        SettingsUpdateResult: {
            applied: boolean;
            /** @description Unified diff of the YAML against the running configuration. */
            diff: string;
            settings: components["schemas"]["Settings"];
        };
        /** @description US dollars per million tokens. An estimate of work done, not a bill. */
        ModelPrice: {
            provider: string;
            model: string;
            input: number;
            output: number;
            cacheRead: number;
            cacheWrite: number;
        };
    };
    responses: never;
    parameters: {
        UserId: string;
        TokenId: string;
        /** @description A vendor account id. Not a UUID — the upstream credential identifier. */
        AccountId: string;
        /** @description Defaults to 7 days before `to`. */
        From: string;
        /** @description Defaults to now. */
        To: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. The body is the same as `GET /api/me`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description `invalid_credentials` — deliberately identical for an unknown address, a wrong password, a blocked user and a service account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `locked_out` — too many failed attempts for this address; `rate_limited` — too many attempts from this client. Both carry `Retry-After`. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startOIDC: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the identity provider. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `oidc_disabled` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    oidcCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back into the application. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Changed. A restricted session becomes a full one. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `weak_password` or `empty_password`, with `field`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `invalid_credentials` — the current password is wrong or the temporary one expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    listMyTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's API tokens, newest first, revoked ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
        };
    };
    issueMyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueTokenRequest"];
            };
        };
        responses: {
            /** @description Issued. `secret` is shown here and never again. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedToken"];
                };
            };
            /** @description `invalid_input` with `field: label` — empty, longer than 64 characters, or with control characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeMyToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. Takes effect on the next proxied request. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found` — also for a token owned by someone else. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMyUsage: {
        parameters: {
            query?: {
                /** @description Defaults to 7 days before `to`. */
                from?: components["parameters"]["From"];
                /** @description Defaults to now. */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated consumption for the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
        };
    };
    getConnectInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment addresses. The client holds the per-tool templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectInfo"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account, humans and service accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created. For a human with local sign-in, `temporaryPassword` is set and shown only here. A service account and an OIDC-only invitation get none. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUser"];
                };
            };
            /** @description `email_taken` — compared case-insensitively. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `invalid_input` with `field` naming the offending field (kind, email, role, signIn, displayName), or `invalid_rule` with `field` set to the first bad rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated. A policy change applies on the user's next request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description `policy_managed_by_idp` — the policy is recomputed at every IdP login and cannot be edited here while the group mapping is configured. `self_lockout` — an administrator tried to block themselves or remove their own admin role. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `invalid_rule` with `field` set to the offending rule. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The temporary password, shown only here. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"];
                };
            };
            /** @description `not_local` — a service account has no password. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renewUserInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invited. The first IdP sign-in with the account's address claims it. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `already_linked` — the account already has an identity-provider link; `not_invitable` — a service account, an account without an email address, or identity-provider sign-in is not configured. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listUserTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description That account's tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
        };
    };
    issueUserToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueTokenRequest"];
            };
        };
        responses: {
            /** @description Issued. `secret` is shown here and never again. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedToken"];
                };
            };
            /** @description `invalid_input` with `field: label` — empty, longer than 64 characters, or with control characters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeUserToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
                tokenId: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found` — no such token on that account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserActivity: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent proxied requests and recent audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The live catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    previewPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyPreviewRequest"];
            };
        };
        responses: {
            /** @description Coverage and per-rule parse errors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyPreview"];
                };
            };
        };
    };
    listProviderAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vendor accounts the gateway holds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAccount"][];
                };
            };
        };
    };
    startProviderLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderLoginStartRequest"];
            };
        };
        responses: {
            /** @description A pending login. The administrator opens `authURL` in their own browser, completes the vendor sign-in, and pastes the URL they land on into `complete` before `expiresAt`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderLoginSession"];
                };
            };
            /** @description `unsupported_provider` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeProviderLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderLoginCompleteRequest"];
            };
        };
        responses: {
            /** @description The account was added and is routable. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAccount"];
                };
            };
            /** @description `login_expired` — the session timed out or was already used. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `login_failed` — the vendor rejected the callback. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeProviderAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A vendor account id. Not a UUID — the upstream credential identifier. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed from memory and from storage. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProviderAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A vendor account id. Not a UUID — the upstream credential identifier. */
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled: boolean;
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAccount"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Validated, and applied unless `dryRun`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResult"];
                };
            };
            /** @description `invalid_settings` or `forbidden_setting` (a field the gateway owns, such as the listen address, the auth directory, the management secret or config API keys), with `field` naming it. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The price list used to estimate cost in metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPrice"][];
                };
            };
        };
    };
    replacePrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelPrice"][];
            };
        };
        responses: {
            /** @description Replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPrice"][];
                };
            };
            /** @description `invalid_input` with `field` naming the entry and value, e.g. `[2].input` (a negative price) or `[3]` (a provider and model listed twice). Nothing is replaced. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
